name: quick_loop
description: Jogo Mobile

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  assets:
  - assets/sounds/ponto.mp3
  - assets/sounds/perdeu.mp3

  uses-material-design: true
